# ========================================== #
#             EmpeDrops Config               #
# ========================================== #

settings:
  inventory-title: "&8&lDROP ZE STONE"
  turbo-multiplier: 2.0

  # Wiadomosc przy znalezieniu przedmiotu
  stone-message: "&6&l[!] &7Znalazles: {ITEM} &8(&e+1&8)"

# Szanse podane w % dla poziomow fortuny: [Brak, Fortuna 1, Fortuna 2, Fortuna 3]
drops:
  DIAMENT:
    material: DIAMOND
    name: "&b&lDIAMENT"
    chances: [0.45, 0.47, 0.50, 0.51]
    exp: 10
    slot: 20
  ZLOTO:
    material: GOLD_INGOT
    name: "&6&lZLOTO"
    chances: [0.80, 0.90, 1.00, 1.20]
    exp: 5
    slot: 21
  ZELAZO:
    material: IRON_INGOT
    name: "&f&lZELAZO"
    chances: [1.20, 1.40, 1.60, 2.00]
    exp: 3
    slot: 22
  EMERALD:
    material: EMERALD
    name: "&a&lEMERALD"
    chances: [0.30, 0.35, 0.40, 0.45]
    exp: 8
    slot: 23
  WEGIEL:
    material: COAL
    name: "&8&lWEGIEL"
    chances: [2.0, 2.2, 2.5, 3.0]
    exp: 1
    slot: 24
  OBSYDIAN:
    material: OBSIDIAN
    name: "&5&lOBSYDIAN"
    chances: [0.10, 0.12, 0.15, 0.18]
    exp: 15
    slot: 11
  PERLA:
    material: ENDER_PEARL
    name: "&d&lPERLA ENDERMANA"
    chances: [0.05, 0.06, 0.08, 0.10]
    exp: 20
    slot: 15

# Wiadomosci TurboDropu
messages:
  no-permission: "&cNie masz uprawnien do tej komendy!"
  player-offline: "&cTen gracz jest aktualnie offline!"
  usage: "&cPoprawne uzycie: /turbodrop <nick/all> <minuty>"
  global-start: "&8&l&m---------------------------------------"